// data.js
export const data = {
  departments: ["Computer Science", "Mechanical Engineering", "Electrical Engineering", "Civil Engineering", "Information Technology","AI/ML","AI/DS"],
  academicYears: ["First Year", "Second Year", "Third Year", "Fourth Year"],

  skills: {
    "Computer Science": ["Data Structures & Algorithms", "Python",
      "JavaScript (React)",
      "Java (Spring Boot)",
      "Cybersecurity (Penetration Testing)",
      "SQL (MySQL)",
      "Cloud Computing (AWS)",
      "Mobile App Development (React Native)",
      "Game Development (Unity)",
      "DevOps (Docker, Kubernetes)",
      "Machine Learning (TensorFlow)", " JavaScript"],
    "Mechanical Engineering": [ "CAD Software (SolidWorks, AutoCAD)",
      "Finite Element Analysis (ANSYS)",
      "Thermodynamics",
      "Fluid Mechanics",
      "Mechanical Design (3D Modeling)",
      "Manufacturing Processes (CNC Machining, 3D Printing)",
      "Programming (Python, MATLAB)",
      "HVAC Systems Design",
      "Robotics (Arduino, Raspberry Pi)",
      "Materials Science (Metallurgy, Polymers)"],
    "Electrical Engineering": ["Circuit Analysis", "Power Systems", "Electronics", "Signal Processing", "Circuit Design (CAD Software)",
      "Control Systems (PLC Programming)",
      "Digital Signal Processing (MATLAB)",
      "Power Systems Analysis (Load Flow Studies)",
      "Electromagnetic Theory (Maxwell's Equations)",
      "Microcontroller Programming (Arduino, Raspberry Pi)",
      "Renewable Energy Systems (Solar Panel Design)",
      "Fault Analysis (Root Cause Analysis)",
      "Simulation Software (SPICE, PSCAD)",
      "Data Analysis (Statistical Methods)"],
    "Civil Engineering": [ "Structural Analysis (Finite Element Method)",
      "Geotechnical Engineering (Soil Testing Techniques)",
      "Transportation Engineering (Traffic Flow Analysis)",
      "Environmental Impact Assessment (EIA Procedures)",
      "Construction Management Software (Primavera, MS Project)",
      "Water Resources Engineering (Hydraulic Modeling)",
      "Building Information Modeling (BIM Tools)",
      "Surveying Techniques (Total Station, GPS)",
      "Material Testing (Concrete and Soil Testing)",
      "Urban Planning Principles (Zoning Regulations)"],
    "Information Technology": ["Network Configuration (Cisco)",
      "Cloud Services (Azure)",
      "IT Support (Help Desk Software)",
      "Database Administration (PostgreSQL)",
      "Systems Integration (API Development)",
      "Cybersecurity Fundamentals (Firewall Management)",
      "Virtualization Technologies (VMware)",
      "IT Project Management (Agile Methodologies)",
      "Business Intelligence Tools (Tableau)",
      "Software Testing (Selenium)"],
      "AI/DS":[ "SQL",
        "Data Visualization (Tableau, Matplotlib)",
        "Big Data Technologies (Hadoop, Spark)",
        "Statistical Analysis (R, Python)",
        "Data Mining Techniques",
        "A/B Testing Methodologies",
        "Machine Learning Model Deployment (Flask, Docker)",
        "Time Series Analysis",
        "Data Wrangling (Pandas)",
        "Business Intelligence Tools"],
      "AI/ML": ["Machine Learning (TensorFlow)",  "Python",
        "R",
        "TensorFlow",
        "PyTorch",
        "Natural Language Processing (NLP)",
        "Computer Vision (OpenCV)",
        "Reinforcement Learning (OpenAI Gym)",
        "Machine Learning Algorithms (Random Forest, SVM)",
        "Data Preprocessing (Pandas, NumPy)",
        "Cloud AI Services (AWS SageMaker)"]
  },

  interests: {
    "Computer Science": ["Open Source Contribution", "Hackathons", "Startups", "Research", "Software Development Life Cycle",
      "User Experience Design",
      "Ethical Hacking",
      "Data Analysis with Pandas",
      "Cloud Architecture",
      "Mobile User Interface Design",
      "Game Mechanics and Design",
      "Continuous Integration/Deployment Practices",
      "Data Science and Analytics",
      "Decentralized Applications (Ethereum)"],
    "Mechanical Engineering": ["Open Source Contribution", "Hackathons", "Startups", "Research", "Automobile Design", "Material Science", "Renewable Energy", "Manufacturing Systems",    "Product Development",
      "Energy Efficiency Solutions",
      "Automation and Control Systems",
      "Prototyping and Testing",
      "Sustainable Manufacturing Practices",
      "Mechanical System Optimization",
      "Advanced Data Analysis in Engineering",
      "Robotics Applications in Industry",
      "Innovative Material Usage",
      "Mechanical Systems Reliability and Maintenance"
  ],
    "Electrical Engineering": ["Open Source Contribution", "Hackathons", "Startups", "Research", "Renewable Energy", "Embedded Systems", "Automation", "IoT",  "Electronics Prototyping",
      "Automation and Robotics",
      "Wireless Communication Technologies",
      "Electrical Safety Standards",
      "Sustainable Energy Solutions",
      "Smart Grid Technologies",
      "Embedded Systems Development",
      "Troubleshooting Electrical Systems",
      "Innovative Circuit Solutions",
      "Research in Electromagnetics"],
    "Civil Engineering": ["Open Source Contribution", "Hackathons", "Startups", "Research", "Green Building", "Urban Planning", "Construction Management", "Environmental Protection", "Sustainable Urban Development",
      "Infrastructure Resilience",
      "Environmental Conservation Practices",
      "Smart City Innovations",
      "Project Lifecycle Management",
      "Community Engagement in Planning",
      "Transportation Safety Improvements",
      "Renewable Construction Materials",
      "Disaster Risk Reduction Strategies",
      "Historical Preservation in Civil Projects"],
    "Information Technology": ["Network Security Protocols",
      "Cloud Infrastructure Management",
      "Customer Relationship Management Systems",
      "Data Warehousing Techniques",
      "System Performance Optimization",
      "Risk Assessment and Mitigation",
      "IT Governance Frameworks",
      "Team Collaboration Tools (Slack, Trello)",
      "Data Visualization Techniques in BI"],
      "AI/DS":[   "Market Research Analysis",
        "Customer Behavior Insights",
        "Financial Forecasting",
        "Sports Analytics",
        "Social Media Analytics",
        "Data Governance and Compliance",
        "Interactive Dashboards Development",
        "Operational Efficiency Improvement",
        "Data Storytelling",
        "Strategic Planning with Data Insights"],
      "AI/ML":[ "Predictive Modeling",
        "Speech Recognition",
        "Image Classification",
        "Autonomous Systems",
        "AI Ethics and Fairness",
        "Robotics Applications",
        "Data-Driven Decision Making",
        "Algorithm Optimization",
        "Neural Networks Design",
        "AI in Healthcare"]
  },

  colleges: {
    Mumbai: ["Mumbai Institute of Technology", "Mumbai College of Engineering", "National Institute of Mumbai"],
    Pune: ["Pune Institute of Engineering", "Pune National College", "Pune Tech University"],
    Dhule: ["Dhule College of Technology", "Dhule National Engineering College", "SVKM'S Institute of Technology"]
  },

  locations: {
    Mumbai: ["Andheri", "Bandra", "Dadar", "Goregaon", "Powai"],
    Pune: ["Shivaji Nagar", "Hinjewadi", "Kothrud", "Viman Nagar"],
    Dhule: ["Deopur", "Malegaon", "Sakri", "Dhule City"]
  }
};
